# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems:
  - jekyll-assets
  - patternfly-sass


# Site settings
title: ManageIQ
email: contact@manageiq.org
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://manageiq.org" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown

exclude:
  - data
  - lib
  - source
  - create-post.rb
  - Gemfile*
  - Guardfile
  - LICENSE.md
  - README.md
  - setup.sh
  - "*.yaml"

# Keep things built externally
keep_files: ["docs/master"]

collections:
  dev_docs:
    output: true
    permalink: /docs/dev/:path

defaults:
  - scope:
      path: ""
      type: "dev_docs"
    values:
      layout: document
